version: '3.8'

services:
  app:
    build:
      context: './docker'
      dockerfile: Dockerfile
    container_name: api-php
    ports:
      - "8080:80"
    volumes:
      - '.:/var/www/html'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge